/**
 * Generates supabase/seed.sql from lib/data/seed-data.ts + lib/config/branches.ts
 *   npm run db:seed:generate
 * Runs on Node 22.18+ (native TypeScript type-stripping) — no build step.
 */
import { writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, resolve } from "node:path"
import { branches } from "../lib/config/branches.ts"
import { partCategories, parts, services, trucks } from "../lib/data/seed-data.ts"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null"
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "null"
  if (typeof v === "boolean") return v ? "true" : "false"
  if (Array.isArray(v)) return v.length ? `array[${v.map(q).join(", ")}]::text[]` : "'{}'::text[]"
  if (typeof v === "object") return `${q(JSON.stringify(v))}::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}

const lines: string[] = []
const out = (s = "") => lines.push(s)

out("-- =============================================================================")
out("-- JAC Motors — development seed (GENERATED by scripts/generate-seed.ts — do not edit)")
out("-- SAMPLE DATA: specs and prices are placeholders, replace before production.")
out("-- =============================================================================")
out("begin;")
out()

// ----------------------------------------------------------------- branches
out("-- Branches")
branches.forEach((b, i) => {
  out(
    `insert into public.branches (slug, code, name, address, city, province, region, phone, mobile, is_head_office, offers_sales, offers_parts, offers_service, hours, latitude, longitude, sort_order)
values (${[
      b.slug, b.code, b.name, b.address, b.city, b.province, b.region, b.phone, b.mobile, b.isHeadOffice,
      b.services.includes("sales"), b.services.includes("parts"), b.services.includes("service"),
      b.hours, b.lat, b.lng, i,
    ].map(q).join(", ")})
on conflict (slug) do update set name = excluded.name, address = excluded.address, phone = excluded.phone, mobile = excluded.mobile, hours = excluded.hours;`,
  )
})
out()

// --------------------------------------------------------- part categories
out("-- Part categories")
for (const c of partCategories) {
  out(
    `insert into public.part_categories (slug, name, description, icon, sort_order) values (${[c.slug, c.name, c.description, c.icon, c.sortOrder].map(q).join(", ")})
on conflict (slug) do update set name = excluded.name, description = excluded.description, icon = excluded.icon, sort_order = excluded.sort_order;`,
  )
}
out()

// ------------------------------------------------------------------ trucks
out("-- Trucks")
for (const t of trucks) {
  out(
    `insert into public.trucks (slug, stock_number, title, brand, model, series, variant, body_type, year, condition, availability, payload_tons, gvw_kg, wheel_config, engine, displacement_cc, horsepower, torque_nm, transmission, fuel_type, emission_standard, wheelbase_mm, mileage_km, color, price, price_on_request, summary, description, features, specs, branch_id, is_featured, is_published)
values (${[
      t.slug, t.stockNumber, t.title, t.brand, t.model, t.series, t.variant, t.bodyType, t.year,
    ].map(q).join(", ")}, ${q(t.condition)}::public.truck_condition, ${q(t.availability)}::public.truck_availability, ${[
      t.payloadTons, t.gvwKg, t.wheelConfig, t.engine, t.displacementCc, t.horsepower, t.torqueNm,
      t.transmission, t.fuelType, t.emissionStandard, t.wheelbaseMm, t.mileageKm, t.color, t.price,
      t.priceOnRequest, t.summary, t.description, t.features, t.specs,
    ].map(q).join(", ")}, (select id from public.branches where slug = ${q(t.branchSlug)}), ${q(t.isFeatured)}, true)
on conflict (slug) do nothing;`,
  )
  t.images.forEach((im, i) => {
    out(
      `insert into public.truck_images (truck_id, url, alt, width, height, sort_order, is_primary)
select id, ${[im.url, im.alt, im.width, im.height, i, im.isPrimary ?? i === 0].map(q).join(", ")} from public.trucks where slug = ${q(t.slug)}
  and not exists (select 1 from public.truck_images ti join public.trucks tr on tr.id = ti.truck_id where tr.slug = ${q(t.slug)} and ti.url = ${q(im.url)});`,
    )
  })
}
out()

// ------------------------------------------------------------------- parts
out("-- Parts + compatibility")
for (const p of parts) {
  out(
    `insert into public.parts (slug, part_number, oem_number, name, brand, category_id, summary, description, specs, price, price_on_request, unit, stock_qty, reorder_level, lead_time_days, weight_kg, image_url, is_published)
values (${[p.slug, p.partNumber, p.oemNumber, p.name, p.brand].map(q).join(", ")}, (select id from public.part_categories where slug = ${q(p.categorySlug)}), ${[
      p.summary, p.description, p.specs, p.price, p.priceOnRequest, p.unit, p.stockQty, p.reorderLevel,
      p.leadTimeDays, p.weightKg, p.imageUrl,
    ].map(q).join(", ")}, true)
on conflict (part_number) do nothing;`,
  )
  for (const c of p.compatibility) {
    out(
      `insert into public.part_compatibility (part_id, model, series, engine, year_from, year_to, notes)
select id, ${[c.model, c.series ?? null, c.engine ?? null, c.yearFrom ?? null, c.yearTo ?? null, c.notes ?? null].map(q).join(", ")} from public.parts where part_number = ${q(p.partNumber)}
on conflict do nothing;`,
    )
  }
}
out()

// ---------------------------------------------------------------- services
out("-- Services")
for (const s of services) {
  out(
    `insert into public.services (slug, name, category, summary, description, inclusions, est_duration_hours, starting_price, interval_km, interval_months, is_package, sort_order)
values (${q(s.slug)}, ${q(s.name)}, ${q(s.category)}::public.service_category, ${[
      s.summary, s.description, s.inclusions, s.estDurationHours, s.startingPrice, s.intervalKm,
      s.intervalMonths, s.isPackage, s.sortOrder,
    ].map(q).join(", ")})
on conflict (slug) do update set name = excluded.name, summary = excluded.summary, description = excluded.description, inclusions = excluded.inclusions;`,
  )
}
out()
out("commit;")
out()

const target = resolve(root, "supabase/seed.sql")
writeFileSync(target, lines.join("\n"))
console.log(`Wrote ${target} — ${branches.length} branches, ${trucks.length} trucks, ${parts.length} parts, ${services.length} services`)
